### ISSUE TITLE
[FAIL. Reason: EvmError: Revert]

### ISSUE THREAD

**Issue by ghostcyber99** [Cyfrin/foundry-fund-me-f23#40]
I am having an issue with foundry 0.2.0 

when I run the forge test 

I get this error  `[FAIL. Reason: EvmError: Revert]`  for the `testPriceFeedVersionIsAccurate() ` function 

but if I fork the test using `forge test -vvvv --fork-url $SEPOLIA_RPC_URL` everything passes 

tried but anvil and ganache but if the error 

thank you in advance

**Comment by Akash-Kolekar** [comment]
I encountered the same error while following along,

If you were following along with him(Patrick) you couldn't have passed the test with Anvil because we didn't write a HelperConfig.sol contract for Anvil then.

Once you finished the contract run every test it passes all the tests with Anvil, Sepolia, and Mainnet.
